// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQL-8c4hmavQPsYJKZz66VEn3P3K3AEBM',
    appId: '1:532243801060:web:30f3b934b1e16376b61df1',
    messagingSenderId: '532243801060',
    projectId: 'travalbooksocial',
    authDomain: 'travalbooksocial.firebaseapp.com',
    storageBucket: 'travalbooksocial.firebasestorage.app',
    measurementId: 'G-RL75WK2KL5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqeiPh7h3XE-5Pr8Hp-ONishiXVhaBuiw',
    appId: '1:532243801060:android:81111672f24ac402b61df1',
    messagingSenderId: '532243801060',
    projectId: 'travalbooksocial',
    storageBucket: 'travalbooksocial.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-wmGVUNbEBlIUcgce9Coe1nI9CU4zOuE',
    appId: '1:532243801060:ios:db243676377efba9b61df1',
    messagingSenderId: '532243801060',
    projectId: 'travalbooksocial',
    storageBucket: 'travalbooksocial.firebasestorage.app',
    iosBundleId: 'com.example.travalBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-wmGVUNbEBlIUcgce9Coe1nI9CU4zOuE',
    appId: '1:532243801060:ios:db243676377efba9b61df1',
    messagingSenderId: '532243801060',
    projectId: 'travalbooksocial',
    storageBucket: 'travalbooksocial.firebasestorage.app',
    iosBundleId: 'com.example.travalBook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQL-8c4hmavQPsYJKZz66VEn3P3K3AEBM',
    appId: '1:532243801060:web:c8f0e711b15d9314b61df1',
    messagingSenderId: '532243801060',
    projectId: 'travalbooksocial',
    authDomain: 'travalbooksocial.firebaseapp.com',
    storageBucket: 'travalbooksocial.firebasestorage.app',
    measurementId: 'G-HLW52FDXMZ',
  );

}